### ISSUE TITLE
The media could not be loaded, either because the server or network failed or because the format is not supported.

### ISSUE THREAD

**Issue by yurifoxx** [AlvaradoAdam15/LaravelTube#8]
Im with the message:
`The media could not be loaded, either because the server or network failed or because the format is not supported. `
in the player, what can be the problem ?

**Comment by deltcod** [comment]
What format do you use? And what file size have?

**Comment by yurifoxx** [comment]
im using .mp4 files and 1mb file

**Comment by nicholasxuu** [comment]
need to use ffmpeg. that will convert new upload to playable format.
seems like the video player only support webm.

**Comment by yurifoxx** [comment]
Hmmm

Em sex, 29 de set de 2017 às 04:45, Nicholas <notifications@github.com>
escreveu:

**Comment by yurifoxx** [comment]
i've just installed ffmpeg and not works yet :(

2017-09-29 10:33 GMT-03:00 Yuri Foxx <ydiretor@gmail.com>:

**Comment by yurifoxx** [comment]
![screenshot-whatsfck dev-2017-09-30-11-12-52-958](https://user-images.githubusercontent.com/4092993/31046523-5f61f8f0-a5d0-11e7-8c52-f83a6d8c324c.png)

**Comment by deltcod** [comment]
Have you tried with another browser?

**Comment by yurifoxx** [comment]
Um using Google Chrome

Em seg, 2 de out de 2017 às 05:41, Adam Alvarado <notifications@github.com>
escreveu:

**Comment by deltcod** [comment]
That is an error of Video.js. Can you try with another browser? For example Firefox. Also look if the video is transformed when you upload it in in other format.

**Comment by yurifoxx** [comment]
@deltcod same error on Firefox too

**Comment by deltcod** [comment]
@yurifoxx When you upload new video,  is it saved with other format? Or only in .mp4? (You can view in console if ffmpeg is running)

**Comment by yurifoxx** [comment]
@deltcod 
The Browser does not find the file for some reason .. but I did not change anything in the code .. 

![image](https://user-images.githubusercontent.com/4092993/31512900-e055793c-af62-11e7-91b3-d04398a12887.png)

**Comment by yurifoxx** [comment]
Not Resolved.
